name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # We need Postgres and Redis to run our Integration Tests
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ledger_admin
          POSTGRES_PASSWORD: securepassword
          POSTGRES_DB: payment_core
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and run concurrency tests
        run: mvn clean verify